# Generated by Django 5.0.1 on 2024-01-29 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('grupo', models.IntegerField()),
                ('sacalibro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigolibro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=128)),
                ('autor', models.CharField(max_length=100)),
                ('ilustrador', models.CharField(blank=True, max_length=100, null=True)),
                ('fechapublicacion', models.IntegerField(blank=True, null=True)),
                ('editorial', models.CharField(max_length=100)),
                ('numerotomo', models.CharField(blank=True, max_length=100, null=True)),
                ('caracteristicasespeciales', models.TextField(blank=True, null=True)),
                ('dewy', models.CharField(blank=True, max_length=45, null=True)),
                ('publicodirigido', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('clavecopia', models.AutoField(primary_key=True, serialize=False)),
                ('disponible', models.BooleanField(default=True)),
                ('clavealumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblio_app.alumno')),
                ('codigolibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.libro')),
            ],
        ),
    ]
