# Generated by Django 5.0.1 on 2024-01-31 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('regreso', models.DateField(null=True)),
                ('fecha_regreso', models.DateField(null=True)),
                ('clave_alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biblio_app.alumno')),
                ('clave_copia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biblio_app.copia')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('pagado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblio_app.alumno')),
                ('prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblio_app.prestamo')),
            ],
        ),
    ]
