# Generated by Django 5.0.1 on 2024-01-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('codigolibro', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=128)),
                ('autor', models.CharField(max_length=100)),
                ('ilustrador', models.CharField(blank=True, max_length=100, null=True)),
                ('fechapublicacion', models.DateField(blank=True, null=True)),
                ('editorial', models.CharField(max_length=100)),
                ('numerotomo', models.CharField(blank=True, max_length=100, null=True)),
                ('caracteristicasespeciales', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('ubicacionbiblio', models.CharField(blank=True, max_length=45, null=True)),
                ('publicodirigido', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
