# Generated by Django 4.2.10 on 2024-03-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0004_alumno_clase_libro_item_libro_palabrasclave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='actualiz',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multa',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio_app.alumno'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='prestamo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio_app.prestamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='clave_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.alumno'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='clave_copia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.copia'),
        ),
    ]
